---
- name: Create Prometheus and Grafana directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ project_dir }}/prometheus"
    - "{{ project_dir }}/grafana/provisioning/datasources"
    - "{{ project_dir }}/grafana/provisioning/dashboards"

- name: Upload configuration files and 01-add-monitoring.yml
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: prometheus.yml.j2, dest: "{{ project_dir }}/prometheus/prometheus.yml", mode: '0644' }
    - { src: datasource.yml.j2, dest: "{{ project_dir }}/grafana/provisioning/datasources/datasource.yml", mode: '0644' }
    - { src: 01-add-monitoring.yml.j2, dest: "{{ project_dir }}/01-add-monitoring.yml", mode: '0600' }

- name: Upload Grafana dashboards files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ project_dir }}/grafana/provisioning/dashboards"
    mode: '0644'
  loop:
    - default.yml
    - patroni.json
    - postgresql.json

# Due to the issue described here https://github.com/grafana/grafana/issues/10786
# the dashboard files need to be edited before provisioning
#
# - name: Upload Grafana dashboards
#   ansible.builtin.uri:
#     url: "https://grafana.com/api/dashboards/{{ item.id }}/revisions/{{ item.revision }}/download"
#     method: GET
#     dest: "{{ project_dir }}/grafana/provisioning/dashboards/{{ item.file_name}}.json"
#     return_content: true
#   loop:
#     - "{{ pgscv_dashboards.patroni }}"
#     - "{{ pgscv_dashboards.postgresql }}"
#     # - "{{ pgscv_dashboards.pgbouncer }}"

- name: Start pgSCV, Prometheus and Grafana containers
  community.docker.docker_compose_v2:
    project_src: "{{ project_dir }}"
    files:
      - docker-compose-patroni.yml
      - 01-add-monitoring.yml
    state: present
