---
- name: Create Redmine project directory
  ansible.builtin.file:
    path: "{{ project_dir }}"
    state: directory
    mode: '0700'

- name: Upload docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ project_dir }}/docker-compose.yml"
    mode: '0600'

- name: Start PostgreSQL and Redmine containers
  community.docker.docker_compose_v2:
    project_src: "{{ project_dir }}"
    files: docker-compose.yml
    state: present
