---
- name: Stop Redmine container
  community.docker.docker_compose_v2:
    project_src: "{{ project_dir }}"
    files: docker-compose.yml
    services: "{{ redmine_service_name }}"
    state: stopped

- name: Create Redmine database dump
  community.postgresql.postgresql_db:
    login_host: localhost
    port: "{{ db_service_port }}"
    login_user: "{{ redmine_user_name }}"
    login_password: "{{ redmine_user_password }}"
    name: "{{ redmine_db_name }}"
    state: dump
    target: "{{ project_dir }}/redmine_db_dump.sql"

- name: Change Redmine database dump file permissions
  ansible.builtin.file:
    path: "{{ project_dir }}/redmine_db_dump.sql"
    mode: '0600'

- name: Remove PostgreSQL and Redmine containers and volumes
  community.docker.docker_compose_v2:
    project_src: "{{ project_dir }}"
    files: docker-compose.yml
    state: absent
    remove_volumes: true

- name: Ensure the Redmine network is removed
  community.docker.docker_network:
    name: "{{ redmine_network_name }}"
    state: absent
