---
- name: Add PostgreSQL GPG key
  ansible.builtin.apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

- name: Add PostgreSQL repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt {{ ansible_lsb.codename }}-pgdg main
    state: present

- name: Install packages required by the Ansible Community.Postgresql collection
  ansible.builtin.apt:
    update_cache: true
    name:
      - postgresql-client-17
      - python3-psycopg2
    state: present
