#!/bin/sh

readonly CONTAINER_IP=$(hostname --ip-address)
readonly CONTAINER_API_ADDRESS="${CONTAINER_IP}:${PATRONI_API_CONNECT_PORT}"
readonly CONTAINER_POSTGRESQL_ADDRESS="${CONTAINER_IP}:5432"
readonly PATRONI_SCOPE="${PATRONI_SCOPE:-patroni}"

export PATRONI_SCOPE
export PATRONI_NAME="${PATRONI_NAME:-$(hostname)}"
export PATRONI_RESTAPI_CONNECT_ADDRESS="$CONTAINER_API_ADDRESS"
export PATRONI_RESTAPI_LISTEN="$CONTAINER_API_ADDRESS"
export PATRONI_POSTGRESQL_CONNECT_ADDRESS="$CONTAINER_POSTGRESQL_ADDRESS"
export PATRONI_POSTGRESQL_LISTEN="$CONTAINER_POSTGRESQL_ADDRESS"
export PATRONI_REPLICATION_USERNAME="${PATRONI_REPLICATION_USERNAME:-replicator}"
export PATRONI_REPLICATION_PASSWORD="${PATRONI_REPLICATION_PASSWORD:-replicate}"
export PATRONI_SUPERUSER_USERNAME="${PATRONI_SUPERUSER_USERNAME:-postgres}"
export PATRONI_SUPERUSER_PASSWORD="${PATRONI_SUPERUSER_PASSWORD:-postgres}"

exec patroni /etc/patroni.yml
