---
- name: Gather PostgreSQL servers roles information
  community.postgresql.postgresql_info:
    login_host: localhost
    port: "{{ item.port }}"
    login_user: "{{ postgres_superuser_username }}"
    login_password: "{{ postgres_superuser_password }}"
    filter: in_recovery
  loop:
    - { name: "{{ postgres_patroni1_name }}", port: "{{ postgres_patroni1_db_port }}" }
    - { name: "{{ postgres_patroni2_name }}", port: "{{ postgres_patroni2_db_port }}" }
    - { name: "{{ postgres_patroni3_name }}", port: "{{ postgres_patroni3_db_port }}" }
  register: pg_servers_roles
  retries: 10
  delay: 5

- name: Create pg_stat_statements database extension
  community.postgresql.postgresql_ext:
    login_host: localhost
    port: "{{ item.item.port }}"
    login_user: "{{ postgres_superuser_username }}"
    login_password: "{{ postgres_superuser_password }}"
    login_db: "{{ redmine_db_name }}"
    name: pg_stat_statements
    state: present
  when: not item.in_recovery
  loop: "{{ pg_servers_roles.results }}"
  loop_control:
    label: "{{ item.item.name }}"

- name: Create VictoriaMetrics and Grafana directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ project_dir }}/victoriametrics/vmagent"
    - "{{ project_dir }}/grafana/provisioning/datasources"
    - "{{ project_dir }}/grafana/provisioning/dashboards"

- name: Upload configuration files and 01-add-monitoring.yml
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: vmagent.yml.j2, dest: "{{ project_dir }}/victoriametrics/vmagent/vmagent.yml", mode: '0644' }
    - { src: datasource.yml.j2, dest: "{{ project_dir }}/grafana/provisioning/datasources/datasource.yml", mode: '0644' }
    - { src: 01-add-monitoring.yml.j2, dest: "{{ project_dir }}/01-add-monitoring.yml", mode: '0600' }

- name: Upload Grafana dashboards files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ project_dir }}/grafana/provisioning/dashboards"
    mode: '0644'
  loop:
    - patroni.json
    - postgresql.json
    - dashboards.yml

# Due to the issue described here https://github.com/grafana/grafana/issues/10786
# the dashboard files need to be edited before provisioning
#
# - name: Upload Grafana dashboards
#   ansible.builtin.uri:
#     url: "https://grafana.com/api/dashboards/{{ item.id }}/revisions/{{ item.revision }}/download"
#     method: GET
#     dest: "{{ project_dir }}/grafana/provisioning/dashboards/{{ item.file_name}}.json"
#     return_content: true
#   loop:
#     - "{{ pgscv_dashboards.patroni }}"
#     - "{{ pgscv_dashboards.postgresql }}"
#     # - "{{ pgscv_dashboards.pgbouncer }}"

- name: Start pgSCV, VictoriaMetrics and Grafana containers
  community.docker.docker_compose_v2:
    project_src: "{{ project_dir }}"
    files:
      - docker-compose-patroni.yml
      - 01-add-monitoring.yml
    state: present
